sudo: true
language: python
python:
  - "3.4"

## http://superuser.com/questions/993718/can-i-install-java-8-on-travis-ci-for-a-python-project
addons:
  apt:
    packages:
      - oracle-java8-installer

# other answer:      
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle   
  
install:
  - "pip install pyyaml"


# command to run tests
script: make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
